---
language: ruby
rvm:
  - 2.6.3

services:
  - docker

env:
  global:
    - ROLE_NAME: prometheus

before_script:
  - sudo pip install ansible-lint yamllint

script:
  - ansible-lint -x 403 -c ./test/lint/.ansible-lint .
  - yamllint --config-file ./test/lint/yaml-lint.yml .
  - bundle exec kitchen test "^uninstall.*(centos|ubuntu-1904|debian-9)" --concurrency

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
